'use client';
import {useRef, useState} from 'react';
import {useLocale, useTranslations} from 'next-intl';
import Link from 'next/link';
import {ArrowUpRight, ArrowRight, MapPin, Camera, Sparkles, Users, X, Sprout, ClipboardList} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {HoyaBoya} from '@/components/mascot';
import {JumpingBonito} from '@/components/jumping-bonito';
import {LogoMark} from '@/components/logo';
import {DuskBanner} from '@/components/backdrop';
import {ScrollHint, Seagulls, Sparks, WaveEdge} from '@/components/motion';
// Each card is a real, open A/B poll (slugs seeded in db/migrations/0009_zz_seed_challenges.sql + supabase/seed.sql).
const cards=[{key:'harbour',place:'place1',art:'harbour-art',slug:'promenade'},{key:'park',place:'place2',art:'park-art',slug:'park'},{key:'street',place:'place3',art:'street-art',slug:'street'}] as const;
export function Home(){
 const t=useTranslations('Home');const locale=useLocale();const dialog=useRef<HTMLDialogElement>(null);const [selected,setSelected]=useState('');const [done,setDone]=useState(false);
 function open(value:string){setSelected(value);setDone(false);dialog.current?.showModal();}
 return <><a className="skip-link" href="#main">{locale==='ja'?'本文へ移動':'Skip to content'}</a><header className="header shell"><Link href={`/${locale}`} className="brand"><LogoMark size={46}/>Citizen Sentiment<span className="brand-dot">.</span></Link><nav aria-label={locale==='ja'?'メインナビゲーション':'Main navigation'}><Link href={`/${locale}/polls`}>{t('polls')}</Link><Link href={`/${locale}/imagine`}>{locale==='ja'?'5年後を想像':'Imagine 2031'}</Link><a href="#challenges">{t('explore')}</a><a href="#surveys">{t('surveys')}</a><a href="#how">{t('about')}</a></nav><Link className="language" href={locale==='ja'?'/en':'/ja'} lang={locale==='ja'?'en':'ja'}>{locale==='ja'?'English ↗':'日本語 ↗'}</Link></header>
 <main id="main"><DuskBanner priority rounded={false} className="flex min-h-[82svh] items-end sm:min-h-[620px]"><Seagulls/><Sparks/><div className="shell relative z-[2] w-full pb-20 pt-24 sm:pb-28"><div className="max-w-xl"><div className="cs-rise location !text-white/85"><span/> {t('location')}</div><p className="cs-rise cs-d1 eyebrow !text-white/85">{t('eyebrow')}</p><h1 className="cs-rise cs-d2 !text-white [text-shadow:0_2px_16px_rgba(0,0,0,.35)]">{t('title')}</h1><p className="cs-rise cs-d3 intro !max-w-lg !text-white/90">{t('intro')}</p><div className="cs-rise cs-d4 hero-actions"><Button asChild className="cs-press cs-shine bg-white !text-[#214e43] hover:bg-[#f1f4ec]"><Link href={`/${locale}/polls`}>{t('cta')}<ArrowUpRight size={18}/></Link></Button><a className="text-link !text-white" href="#how">{t('secondary')} <ArrowRight size={16}/></a></div><p className="cs-rise cs-d5 quiet !text-white/80"><span className="mini-leaf !bg-white/15"><Sprout size={17}/></span>{t('note')}</p></div></div><WaveEdge/><ScrollHint label={locale==='ja'?'下へスクロール':'Scroll down'}/></DuskBanner><span id="main-content"/>
 <div className="preview shell"><span className="preview-dot"/>{t('preview')}</div>
 <section className="shell" aria-label={locale==='ja'?'ホヤぼーやからのお知らせ':'A message from Hoya Boya'}><div className="flex flex-col items-start gap-5 rounded-2xl bg-[#e8eddf] p-5 sm:flex-row sm:items-center sm:justify-between sm:p-7"><HoyaBoya pose="wave" height={130} say={locale==='ja'?'まちの計画、AとBどっちがいい？スマホで投票してね！':'City plans: A or B? Vote on your phone!'}/><Button asChild className="cs-press shrink-0"><Link href={`/${locale}/polls`}>{t('cta')}<ArrowUpRight size={18}/></Link></Button></div></section>

 <section id="challenges" className="section shell"><p className="eyebrow">{t('sectionLabel')}</p><h2>{t('section')}</h2><p className="section-intro">{t('sectionIntro')}</p><div className="cards">{cards.map((card,i)=><article className="challenge" key={card.key}><div className={`card-art ${card.art}`} aria-hidden="true"><span className="sample-tag">{t('tag')}</span><div className="scene-sun"/><div className="scene-ground"/><div className="scene-building a"/><div className="scene-building b"/><div className="scene-tree"/><span className="scene-number">0{i+1}</span></div><div className="card-content"><p className="place"><MapPin size={14}/>{t(card.place)}</p><h3>{t(card.key)}</h3><p>{t(`${card.key}Desc`)}</p><Link className="card-link cs-press" href={`/${locale}/poll/${card.slug}`} aria-label={`${t(card.key)} — ${t('all')}`}>{t('all')}<ArrowUpRight size={20}/></Link></div></article>)}</div></section>
 <section id="surveys" className="survey-banner shell"><div className="survey-icon"><ClipboardList size={56} strokeWidth={1.2}/><span>✦</span></div><div className="survey-copy"><p className="eyebrow">{t('surveyLabel')}</p><h2>{t('surveyTitle')}</h2><p>{t('surveyDesc')}</p></div><div className="survey-action"><Button onClick={()=>open('survey')}>{t('surveyCta')}<ArrowRight size={17}/></Button><p>{t('surveyMeta')}</p></div></section>
 <section id="how" className="section shell how"><p className="eyebrow">CITIZEN SENTIMENT</p><h2>{t('howTitle')}</h2><div className="steps">{[Camera,Sparkles,Users].map((Icon,i)=><div key={i}><span className="step-icon"><Icon size={25}/></span><span className="step-number">0{i+1}</span><h3>{t(`step${i+1}`)}</h3><p>{t(`step${i+1}Desc`)}</p></div>)}</div></section><JumpingBonito/></main><footer className="shell"><div className="footer-top"><Link href={`/${locale}`} className="brand"><LogoMark size={30}/>Citizen Sentiment.</Link><span>{t('footer')}</span></div><p>{t('footerNote')}</p></footer>
 <dialog ref={dialog} className="detail-dialog" onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close();}}><button className="dialog-close" onClick={()=>dialog.current?.close()} aria-label={t('close')}><X/></button>{selected==='survey'?done?<div role="status"><p className="eyebrow">{t('sample')}</p><h2>{t('thanks')}</h2><p>{t('thanksDesc')}</p><Button onClick={()=>dialog.current?.close()}>{t('close')}</Button></div>:<form onSubmit={e=>{e.preventDefault();setDone(true);}}><p className="eyebrow">{t('sample')}</p><h2>{t('surveyTitle')}</h2><fieldset><legend>{t('question1')} *</legend>{[1,2,3].map(i=><label className="option" key={i}><input type="radio" name="priority" value={i} required/>{t(`option${i}`)}</label>)}</fieldset><fieldset><legend>{t('question2')} *</legend><div className="ratings">{[1,2,3,4,5].map(i=><label key={i}><input type="radio" name="rating" value={i} required/><span aria-label={`${i} ${t('rating')}`}>{i}</span></label>)}</div></fieldset><label className="textarea-label">{t('question3')}<textarea maxLength={2000} placeholder={t('placeholder')}/></label><Button type="submit">{t('submit')}<ArrowRight size={17}/></Button></form>:selected?<><p className="eyebrow">{t('tag')}</p><h2>{t(selected)}</h2><p>{t(`${selected}Desc`)}</p><div className="notice">{t('detailNote')}</div><Button onClick={()=>dialog.current?.close()}>{t('close')}</Button></>:null}</dialog></>;
}
